fernetKey: M3N2OU1GRFVrZ0ZwWVY4OXZrUTBGR1JQVkFKSUhTUm0=
webserverSecretKey: M3N2OU1GRFVrZ0ZwWVY4OXZrUTBGR1JQVkFKSUhTUm0=
executor: "KubernetesExecutor"


dags:
  gitSync:
    enabled: true
    repo: https://github.com/PTson2207/k8s.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

logs:
  persistence:
    enabled: true
